import { cn } from "@/utils/helper";
import type { Metadata } from "next";
import { NavBar } from "@/components/NavBar";
import LangProvider from "@/context/LangContext";
import ScrollButton from "@/components/ScrollButton";
import { Roboto, Bebas_Neue } from "next/font/google";
import { FooterSection } from "@/components/FooterSection";

import "./globals.css";
import { Providers } from "@/components/Providers";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LangProvider>
      <html>
        <body
          className={cn(
            roboto.className,
            bebas.variable,
            "bg-zinc-100 text-zinc-900 dark:bg-zinc-900 dark:text-zinc-50"
          )}
        >
          <Providers>
            <NavBar />
            <main className="max-w-7xl mx-auto px-4 md:px-8 flex flex-col gap-20">
              {children}
            </main>
            <FooterSection />
            <ScrollButton />
          </Providers>
        </body>
      </html>
    </LangProvider>
  );
}
