import type { Metadata } from "next";
import { Roboto, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/helper";
import { Navigation } from "@/components/Navigation";
import { HeroSection } from "@/components/HeroSection";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          roboto.className,
          bebas.variable,
          "bg-zinc-900 text-zinc-50"
        )}
      >
        <Navigation />
        <main className="max-w-7xl mx-auto px-4 md:px-8">{children}</main>
      </body>
    </html>
  );
}
