import type { Metadata } from "next";
import { Roboto, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/helper";
import { Navigation } from "@/components/Navigation";
import { FooterSection } from "@/components/FooterSection";
import LangProvider from "@/context/LangContext";
import ScrollButton from "@/components/ScrollButton";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LangProvider>
      <html>
        <body
          className={cn(
            roboto.className,
            bebas.variable,
            "bg-zinc-900 text-zinc-50"
          )}
        >
          <Navigation />
          <main className="max-w-7xl mx-auto px-4 md:px-8 flex flex-col gap-20">
            {children}
          </main>
          <FooterSection />
          <ScrollButton />
        </body>
      </html>
    </LangProvider>
  );
}
